#!/usr/bin/env bash
# Loops 1 to 20 and prints "bad luck" messages for 4, 9, and 17 using case
i=1
while [ $i -le 20 ]
do
    case $i in
        4)
            echo "4 - bad luck from China"
            ;;
        9)
            echo "9 - bad luck from Japan"
            ;;
        17)
            echo "17 - bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    i=$((i+1))
done
