#!/usr/bin/env bash
# Lists files in the current directory, showing only the part after the first dash
for file in *
do
    if [ -f "$file" ]
    then
        echo "$file" | cut -d '-' -f 2-
    fi
done
