#!/usr/bin/env bash
# Checks if the file 'school' exists and its properties
if [ -f "school" ]
then
    echo "school is a regular file"
fi
if [ -s "school" ]
then
    echo "school file is not empty"
elif [ -e "school" ]
then
    echo "school file is empty"
fi
if [ -e "school" ]
then
    echo "school file exists"
fi
if [ ! -e "school" ]
then
    echo "school file does not exist"
fi
